In [114]:
import os
os.environ["LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT"] = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data"

import sys
import requests
from os.path import join, exists, basename
from glob import glob
from label_studio_sdk import Client
from copy import deepcopy

import torch
import numpy as np
from ultralytics.utils.ops import xyxyxyxy2xywhr, xywhr2xyxyxyxy
from ultralytics.utils.metrics import probiou
from tqdm.notebook import tqdm

import matplotlib.pyplot as plt
import warnings

from joblib import Parallel, delayed

# sys.path.append("/home/patel_zeel/kilns_neurips24/scripts")

In [115]:
# @Author: Saurav Kumar
import numpy as np
import torch
from os.path import join, exists, basename
import warnings
from ultralytics.utils.metrics import probiou
from glob import glob
from time import time
from ultralytics.utils.ops import xywhr2xyxyxyxy, xyxyxyxy2xywhr
from typing import Union
label_map = {"face": 0, "nostal": 1}
reverse_label_map = {value: key for key, value in label_map.items()}
def label_studio_to_yolo_obb(x1, y1, w, h, r, label) -> Union[np.ndarray, torch.Tensor]:
    """
    Convert from Label studio CSV (x1, y1, w, h, r) to YOLO OBB (x1, y1, x2, y2, x3, y3, x4, y4) format
    x1: x-cordinate of one corner of the box, range(0, 100)
    y1: y-cordinate of one corner of the box, range(0, 100)
    w: width of the box, range(0, 100)
    h: height of the box, range(0, 100)
    r: rotation angle of the box in degrees
    label: label of the box
    Returns: Label in YOLO OBB format -> array([label_id, x1, y1, x2, y2, x3, y3, x4, y4])
    """
    if isinstance(x1, torch.Tensor):
        handle = torch
        handle.concatenate = torch.cat
        get_array = lambda x: torch.tensor(x)
    else:
        handle = np
        get_array = lambda x: np.array(x)
    r = handle.radians(r)
    cos_rot = handle.cos(r)
    sin_rot = handle.sin(r)
    x_c = x1 + w / 2 * cos_rot - h / 2 * sin_rot
    y_c = y1 + w / 2 * sin_rot + h / 2 * cos_rot
    xywhr = get_array([x_c, y_c, w, h, r])
    xyxyxyxy = xywhr2xyxyxyxy(xywhr).ravel()
    # Normalize to range(0, 1)
    xyxyxyxy = xyxyxyxy / 100
    label_id = get_array([label_map[label]])
    yolo_label = handle.concatenate([label_id, xyxyxyxy])
    return yolo_label




def label_studio_to_yolo_aa(x1, y1, w, h, r, label) -> Union[np.ndarray, torch.Tensor]:
    """
    Convert from Label studio CSV (x1, y1, w, h, r) to YOLO OBB (x1, y1, x2, y2, x3, y3, x4, y4) format
    x1: x-cordinate of one corner of the box, range(0, 100)
    y1: y-cordinate of one corner of the box, range(0, 100)
    w: width of the box, range(0, 100)
    h: height of the box, range(0, 100)
    r: rotation angle of the box in degrees
    label: label of the box
    Returns: label in YOLO format -> array([label_id, x_c, y_c, w, h])
    """
    if isinstance(x1, torch.Tensor):
        handle  = torch
        get_array = lambda x: torch.tensor(x)
    else:
        handle = np
        get_array = lambda x: np.array(x)
    label_id, x1, y1, x2, y2, x3, y3, x4, y4 = label_studio_to_yolo_obb(x1, y1, w, h, r, label)
    x_max = max(x1, x2, x3, x4)
    x_min = min(x1, x2, x3, x4)
    y_max = max(y1, y2, y3, y4)
    y_min = min(y1, y2, y3, y4)
    x_c = (x_max + x_min) / 2
    y_c = (y_max + y_min) / 2
    w = x_max - x_min
    h = y_max - y_min
    xywh = get_array([x_c, y_c, w, h])
    label_id = get_array([label_id])
    # print(label_id.shape, xywh.shape)
    yolo_label = handle.concatenate([label_id, xywh])
    return yolo_label

def to_label_studio_json(x, y, w, h, r, score, label):
    return       {
        "model_version": "one",
        "score": float(score),
        "result": [
          {
            # "id": str(time() + np.random.randn()),
            "type": "rectanglelabels",
            "from_name": "label",
            "to_name": "image",
            "original_width": 256,
            "original_height": 192,
            "image_rotation": 0,
            "value": {
              "rotation": float(r),
              "x": float(x),
              "y": float(y),
              "width": float(w),
              "height": float(h),
              "rectanglelabels": [
                label
              ]
            }
          }
        ]
      }
def yolo_obb_to_label_studio_json(label_id, x1, y1, x2, y2, x3, y3, x4, y4, score):
    """
    Convert from YOLO OBB (x1, y1, x2, y2, x3, y3, x4, y4) to Label studio CSV (x1, y1, w, h, r) format
    label_id: label id of the box
    x1: x-cordinate of one corner of the box, range(0, 1)
    y1: y-cordinate of one corner of the box, range(0, 1)
    x2: x-cordinate of one corner of the box, range(0, 1)
    y2: y-cordinate of one corner of the box, range(0, 1)
    x3: x-cordinate of one corner of the box, range(0, 1)
    y3: y-cordinate of one corner of the box, range(0, 1)
    x4: x-cordinate of one corner of the box, range(0, 1)
    y4: y-cordinate of one corner of the box, range(0, 1)
    Returns: JSON
    """
    if isinstance(x1, torch.Tensor):
        handle = torch
        handle.concatenate = torch.cat
        get_array = lambda x: torch.tensor(x).to(torch.float32)
    else:
        handle = np
        get_array = lambda x: np.array(x).astype(np.float32)
    label = reverse_label_map[label_id]
    array = get_array([x1, y1, x2, y2, x3, y3, x4, y4]).reshape(1, -1)
    # print(array.shape)
    xywhr = xyxyxyxy2xywhr(array).ravel()
    # print(xywhr.shape, xywhr)
    x_c, y_c, w, h = xywhr[:-1] * 100
    r_rad = xywhr[-1]
    cos_rot = handle.cos(xywhr[-1])
    sin_rot = handle.sin(xywhr[-1])
    x = x_c - w / 2 * cos_rot + h / 2 * sin_rot
    y = y_c - w / 2 * sin_rot - h / 2 * cos_rot
    r = handle.degrees(r_rad)
    return to_label_studio_json(x, y, w, h, r, score, label)

def yolo_aa_to_label_studio_json(label_id, x_c, y_c, w, h, score):
    """
    Convert from YOLO AA (x_c, y_c, w, h) to Label Studio JSON format.
    label_id: Label ID from YOLO format.
    x_c, y_c: Center coordinates of the bounding box (normalized: range 0-1).
    w, h: Width and height of the bounding box (normalized: range 0-1).
    score: Confidence score.
    Returns: JSON format for Label Studio.
    """
    if isinstance(x_c, torch.Tensor):
        handle = torch
        get_array = lambda x: torch.tensor(x)
    else:
        handle = np
        get_array = lambda x: np.array(x)
    # Convert Label ID to readable format (if needed)
    label = reverse_label_map[label_id]  # Ensure 'reverse_label_map' is defined
    # Convert from normalized YOLO format (0-1) to Label Studio scale (0-100)
    x_c, y_c, w, h = get_array([x_c, y_c, w, h]) * 100
    # Convert center (x_c, y_c) to top-left (x1, y1) format
    x = x_c - (w / 2)
    y = y_c - (h / 2)
    # Label Studio assumes no rotation for axis-aligned boxes (AA)
    rotation = 0.0
    # Convert to Label Studio format
    label_studio_json = {
        "label": label,
        "x": x,
        "y": y,
        "width": w,
        "height": h,
        "rotation": rotation,
        "score": score
    }
    return label_studio_json

In [116]:
# from utils import yolo_obb_to_label_studio_json

## Label Studio Initialize

In [117]:
LABEL_STUDIO_URL = 'http://10.0.62.168:8081'
API_KEY = '2557d98fa3032fc9a2eb033baf2775ebc2e1a0ef'

ls = Client(url=LABEL_STUDIO_URL, api_key=API_KEY)

## Process the input data

In [118]:

image_read_dir =  "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/pred/predictions2/images"
pred_txt_path = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/pred/predictions2/labels"
ls_project_name = f"random"

pred_files = sorted(glob(join(pred_txt_path, "*.txt")))
pred_base_names = set([basename(f) for f in pred_files])

print(len(pred_files))

10


In [119]:
# pred_txt_path = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/region_performance/"
# image_read_dir = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/region_performance/bihar_0.25/images"

# state = "bihar_0.25"
# version = "250"
# score_threshold = 0.25
# ls_project_name = f"{state}_{version}_{version}"
# print(ls_project_name)
# save_dir = f"/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/pred/{state}_{version}"
# print(save_dir)
# corrected_txt_path = join("/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/pred/", state)
# print(corrected_txt_path)


# pred_files = sorted(glob(join(pred_txt_path, state, "labels", "*.txt")))
# # print(pred_files)
# # print(pred_files)
# pred_base_names = set([basename(f) for f in pred_files])
# corrected_files = sorted(glob(join(corrected_txt_path, "*.txt")))
# corrected_base_names = set([basename(f) for f in corrected_files])

# print(len(pred_files), len(corrected_files))

In [120]:
# common_tiles = []
# uncommon_tiles = []
# for pred_base, pred_full in tqdm(zip(pred_base_names, pred_files)):
#     if pred_base in corrected_base_names:
#         common_tiles.append(pred_base)
#     else:
#         uncommon_tiles.append(pred_full)
# len(common_tiles), len(uncommon_tiles)

Remove lucknow files

In [121]:
# lucknow_files = glob(join("/home/patel_zeel/kilns_neurips24/processed_data/lucknow_sarath_grid_obb_v3/labels", "*.txt"))
# lucknow_base_names = set([basename(f) for f in lucknow_files])

# lucknow_removed_uncommon = []
# for full in tqdm(uncommon_tiles):
#     base = basename(full)
#     if base in lucknow_base_names:
#         pass
#     else:
#         lucknow_removed_uncommon.append(full)
    
# len(lucknow_removed_uncommon)

## Filter further

In [122]:
# set_all_till_now = set(map(basename, glob("/home/patel_zeel/kilns_neurips24/corrected_txt_obb/uttar_pradesh/*.txt")))
# print(len(set_all_till_now))
# print(len(lucknow_removed_uncommon))
# filtered_uncommon = [file for file in lucknow_removed_uncommon if basename(file) not in set_all_till_now]
# len(filtered_uncommon)

In [123]:
# # Save symlink of files
# save_image_dir = f"/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/synthetic_data/west_bengal_to_haryana/images"
# save_label_dir = f"/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/synthetic_data/west_bengal_to_haryana/labels"
# print("saving to", save_image_dir, save_label_dir)
# os.system("rm -rf " + save_image_dir)
# os.system("rm -rf " + save_label_dir)
# os.makedirs(save_image_dir)
# os.makedirs(save_label_dir)

# for tile in tqdm(filtered_uncommon):
#     part = tile.split("/")[-3]
#     name = tile.split("/")[-1].replace(".txt", ".png")
#     image_path = join(image_read_dir, part, name)
#     txt_path = join(pred_txt_path, part, "labels", name.replace(".png", ".txt"))
#     os.symlink(image_path, join(save_image_dir, name))
#     os.symlink(txt_path, join(save_label_dir, name.replace(".png", ".txt")))

# print("image_path", image_path)
# print("txt_path", txt_path)
# print(join(save_image_dir, name))
# print(join(save_label_dir, name.replace(".png", ".txt")))

In [124]:
save_image_dir = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/barisal/images"
save_label_dir = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/barisal/labels"

## Create Project

In [125]:
state = "random_v11"
version = "250"

In [126]:
projects = ls.list_projects()

print(projects)

[<label_studio_sdk._legacy.project.Project object at 0x7f64637ae800>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ae830>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ac9a0>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ac640>, <label_studio_sdk._legacy.project.Project object at 0x7f64637af010>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ade70>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ac9d0>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ae020>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ac580>, <label_studio_sdk._legacy.project.Project object at 0x7f64637af700>, <label_studio_sdk._legacy.project.Project object at 0x7f64637af6a0>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ae560>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ae860>, <label_studio_sdk._legacy.project.Project object at 0x7f64637ae680>, <label_studio_sdk._legacy.project

In [128]:
projects = ls.list_projects()
project = None  # Ensure project is assigned correctly

for proj in projects:
    if proj.title == f"{state}_OBB_{version}":
        print("Project found. Using it...")
        project = proj
        break

if project is None:
    print("No project found. Creating...")
    project = ls.start_project(title=f"{state}_OBB_{version}", label_config='''
<View>
  <Image name="image" value="$image" rotateControl="true" zoomControl="true" zoom="true"/>
  <RectangleLabels name="label" toName="image">
    <Label value="face" background="#FFA39E"/>
    <Label value="nostal" background="#FFA39E"/>
  </RectangleLabels>
</View>
    ''')
    
# ✅ Check storage connections
storages = project.get_import_storages()
if not storages:
    print("No storage found. Creating...")
    project.connect_local_import_storage(save_image_dir, regex_filter=".*tif")
    storages = project.get_import_storages()  # Refresh storage list

if storages:
    storage = storages[0]
    print("Storage found. Using it...")

    if storage.get("last_sync") is None:
        print("Syncing storage...")
        project.sync_storage(storage["type"], storage["id"])
    else:
        print("Storage already synced.")

# ✅ Fetch tasks and verify count
print("Getting tasks...")
tasks = project.get_tasks()
print(f"Total tasks found: {len(tasks)}")


Project found. Using it...
Storage found. Using it...
Storage already synced.
Getting tasks...
Total tasks found: 0


In [111]:
# projects = ls.list_projects()
# for project in projects:
#     if project.title == f"{state}_OBB_{version}":
#         print("Project found. Using it...")
#         break
# else:
#     print("No project found. Creating...")
#     project = ls.start_project(title=f"{state}_OBB_{version}", label_config='''
# <View>
#   <Image name="image" value="$image" rotateControl="true" zoomControl="true" zoom="true"/>
#   <RectangleLabels name="label" toName="image">
    
    
#   <Label value="Inner_Box" background="#FFA39E"/><Label value="Box" background="#FFA39E"/><Label value="Outer_Box" background="#63c205"/></RectangleLabels>
# </View>
#     ''')
# storages = project.get_import_storages()
# if len(storages) == 0:
#     print("No storage found. Creating...")
#     project.connect_local_import_storage(save_image_dir, regex_filter=".*png")
# else:
#     assert len(storages) == 1
#     print("Storage found. Using it...")
# storage = storages[0]
# if storage['last_sync'] is None:
#     print("Syncing storage...")
#     project.sync_storage(storage['type'], storage['id'])
# else:
#     print("Storage already synced.")

# print("Getting tasks...")
# tasks = project.get_tasks()
# len(tasks)

In [112]:
tasks[0]

{'id': 4623,
 'predictions': [],
 'annotations': [],
 'drafts': [],
 'annotators': [],
 'inner_id': 1,
 'cancelled_annotations': 0,
 'total_annotations': 0,
 'total_predictions': 0,
 'completed_at': None,
 'annotations_results': '',
 'predictions_results': '',
 'predictions_score': None,
 'file_upload': None,
 'storage_filename': '/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/pred/predictions2/images/AP_21_Frag_1_minute_1.jpg',
 'annotations_ids': '',
 'predictions_model_versions': '',
 'avg_lead_time': None,
 'draft_exists': False,
 'updated_by': [],
 'data': {'image': '/data/local-files/?d=home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/pred/predictions2/images/AP_21_Frag_1_minute_1.jpg'},
 'meta': {},
 'created_at': '2025-02-18T18:18:52.467306Z',
 'updated_at': '2025-02-18T18:18:52.467323Z',
 'is_labeled': False,
 'overlap': 1,
 'comment_count': 0,
 'unresolved_comment_count': 0,
 'last_comment_updated_at': None,
 'project': 32,
 'comment_authors': []}

In [95]:
# correct cell

# ## Delete all predictions before going ahead
# os.system(f"curl -H 'Authorization: Token {API_KEY}' -X POST \"localhost:8081/api/dm/actions?id=delete_tasks_predictions&project={project.id}\"")

# for task in tqdm(tasks):
#     # part = tile.split("/")[-3]
#     # name = tile.split("/")[-1].replace(".txt", ".png")
#     # image_path = join(save_dir, name)
#     image_path = task['storage_filename']
#     txt_name = basename(image_path).replace(".png", ".txt")
    
#     preds = np.loadtxt(join(save_label_dir, txt_name))
#     preds = np.atleast_2d(preds)

#     results = []
#     for pred in preds:
#         label_id = int(pred[0])
#         x1, y1, x2, y2, x3, y3, x4, y4 = pred[1:-1]
#         score = pred[-1]
#         if score > score_threshold:
#           prediction = yolo_obb_to_label_studio_json(label_id, x1, y1, x2, y2, x3, y3, x4, y4, score)
#           # predictions.append(prediction)
#           results.append(prediction['result'][0])
#     if len(results) > 0:
#       # I have tried parallelizing this but it doesn't work
#       project.create_prediction(task['id'], results, model_version=version)

In [113]:
os.system(f"curl -H 'Authorization: Token {API_KEY}' -X POST \"localhost:8081/api/dm/actions?id=delete_tasks_predictions&project={project.id}\"")
score_threshold=0.25
for task in tqdm(tasks):
    # part = tile.split("/")[-3]
    # name = tile.split("/")[-1].replace(".txt", ".png")
    # image_path = join(save_dir, name)
    image_path = task['storage_filename']
    txt_name = basename(image_path).replace(".jpg", ".txt")
    
    preds = np.loadtxt(join(save_label_dir, txt_name))
    preds = np.atleast_2d(preds)

    results = []

    for pred in preds:
        label_id = int(pred[0])
        print(pred[1:-1])
        x_c, y_c, w, h = pred[1:-1]
        score = pred[-1]
        if score > score_threshold:
          prediction = yolo_aa_to_label_studio_json(label_id, x_c, y_c, w, h, score)
          # predictions.append(prediction)
          results.append(prediction)
    if len(results) > 0:
        # I have tried parallelizing this but it doesn't work
        project.create_prediction(task['id'], results, model_version=version)

{"processed_items":0,"detail":"Deleted 0 predictions"}

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    54  100    54    0     0   1984      0 --:--:-- --:--:-- --:--:--  2000


  0%|          | 0/10 [00:00<?, ?it/s]

[    0.53654     0.38298     0.14798     0.19023]
[     0.5165     0.36007     0.03937    0.039905]
[    0.53404     0.38312     0.14678     0.19042]
[    0.51163     0.36234    0.038043     0.04246]
[    0.53341     0.38297     0.14714     0.19033]
[    0.53387     0.38391     0.14696     0.19137]
[    0.53637     0.38497     0.15129      0.1935]
[    0.52912     0.35736    0.041635    0.040497]
[    0.53588     0.38405     0.14836     0.19128]
[    0.52979     0.35716     0.04038    0.039943]
[    0.53528       0.384     0.14749     0.19047]
[    0.52964     0.35758    0.040501    0.039891]
[    0.52228     0.38887     0.15214      0.1968]
[    0.49924      0.3631    0.038194    0.043898]
[    0.52205     0.38976     0.15717     0.19518]
[    0.49854     0.36688    0.039319    0.044534]
[    0.52299     0.38962     0.15729     0.19452]
[    0.49873     0.36736    0.039541    0.045221]


f

## Appendix

In [ ]:
label_map = {"Inner_Box": 0, "Outer_Box": 1}
reverse_label_map = {v: k for k, v in label_map.items()}


label_map["Box"] = 2  # Add the missing label
reverse_label_map = {v: k for k, v in label_map.items()}
print(f"label_id: {label_id}, reverse_label_map: {reverse_label_map}")

def to_label_studio_json(x, y, w, h, r, score, label):
    return       {
        "model_version": "one",
        "score": float(score),
        "result": [
          {
            # "id": str(time() + np.random.randn()),
            "type": "rectanglelabels",
            "from_name": "label",
            "to_name": "image",
            "original_width": 640,
            "original_height": 640,
            "image_rotation": 0,
            "value": {
              "rotation": float(r),
              "x": float(x),
              "y": float(y),
              "width": float(w),
              "height": float(h),
              "rectanglelabels": [
                label
              ]
            }
          }
        ]
      }
def yolo_obb_to_label_studio_json(label_id, x1, y1, x2, y2, x3, y3, x4, y4, score):
    """
    Convert from YOLO OBB (x1, y1, x2, y2, x3, y3, x4, y4) to Label Studio CSV format.
    """
    
    if isinstance(x1, torch.Tensor):
        handle = torch
        handle.concatenate = torch.cat
        get_array = lambda x: torch.tensor(x).to(torch.float32)
    else:
        handle = np
        get_array = lambda x: np.array(x).astype(np.float32)

    # ✅ Debug print
    print(f"label_id: {label_id}, Available labels: {reverse_label_map.keys()}")

    # ✅ Handle missing labels
    if label_id not in reverse_label_map:
        print(f"Warning: label_id {label_id} not found! Using 'Unknown_Label'.")
        label = "Unknown_Label"
    else:
        label = reverse_label_map[label_id]

    array = get_array([x1, y1, x2, y2, x3, y3, x4, y4]).reshape(1, -1)
    xywhr = xyxyxyxy2xywhr(array).ravel()
    
    x_c, y_c, w, h = xywhr[:-1] * 100
    r_rad = xywhr[-1]

    cos_rot = handle.cos(r_rad)
    sin_rot = handle.sin(r_rad)

    x = x_c - w / 2 * cos_rot + h / 2 * sin_rot
    y = y_c - w / 2 * sin_rot - h / 2 * cos_rot
    r = handle.degrees(r_rad)

    return to_label_studio_json(x, y, w, h, r, score, label)


label_id: 2, reverse_label_map: {0: 'Inner_Box', 1: 'Outer_Box', 2: 'Box'}


In [ ]:
import os
import numpy as np
from tqdm import tqdm
from os.path import join, basename, exists

# Deleting all predictions before proceeding
os.system(f"curl -H 'Authorization: Token {API_KEY}' -X POST \"localhost:8081/api/dm/actions?id=delete_tasks_predictions&project={project.id}\"")

for task in tqdm(tasks):
    image_path = task['storage_filename']
    print(image_path)
    txt_name = basename(image_path).replace(".png", ".txt")
    print(txt_name)
    txt_path = join(pred_txt_path, txt_name)
    
    # Check if the .txt file exists
    if not exists(txt_path):
        # print(f"Skipping {txt_name}: corresponding .txt file not found.")
        continue

    # Load predictions from the .txt file
    preds = np.loadtxt(txt_path)
    preds = np.atleast_2d(preds)

    results = []
    for pred in preds:
        print(pred.shape)
        label_id = int(pred[0])
        print(pred[1:9])

        x1, y1, x2, y2, x3, y3, x4, y4 = pred[1:9]
        score = pred[-1]
    #     # Convert YOLO OBB to Label Studio format
    
        prediction = yolo_obb_to_label_studio_json(label_id, x1, y1, x2, y2, x3, y3, x4, y4, score)
        results.append(prediction['result'][0])

    if len(results) > 0:
    #     # Create prediction in Label Studio
        project.create_prediction(task['id'], results, model_version="v1")


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    54  100    54    0     0   1855      0 --:--:-- --:--:-- --:--:--  1862


{"processed_items":0,"detail":"Deleted 0 predictions"}

100%|██████████| 88/88 [00:00<00:00, 58420.19it/s]

/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/synthetic_data/west_bengal_to_haryana/images/1.jpg
1.jpg
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/synthetic_data/west_bengal_to_haryana/images/img100_png.rf.5b114ad97e6b375451fd868587d9a496.jpg
img100_png.rf.5b114ad97e6b375451fd868587d9a496.jpg
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/synthetic_data/west_bengal_to_haryana/images/img107_png.rf.0ce536fd3f054214cf75c4b2af78f078.jpg
img107_png.rf.0ce536fd3f054214cf75c4b2af78f078.jpg
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/synthetic_data/west_bengal_to_haryana/images/img111_png.rf.36084c39d24ba8242f9275bedbf21bb9.jpg
img111_png.rf.36084c39d24ba8242f9275bedbf21bb9.jpg
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/synthetic_data/west_bengal_to_haryana/images/img112_png.rf.a984847e2602cf7c9af62b4f0a8ffe59.jpg
img112_png.rf.a984847e2602cf7c9af62b4f0a8ffe59.jpg
/home/rishabh.mondal/Brick-Kilns-project

In [ ]:
# areas = []
# for item in json_list:
#     for pred in item["predictions"]:
#         area = pred['result'][0]['value']['width'] * pred['result'][0]['value']['height']
#         area = area * (1120 * 1120) / (100 * 100)
#         areas.append(area)
# len(areas)

In [ ]:
# max(areas), min(areas), np.mean(areas), np.median(areas)

In [ ]:
# import seaborn as sns

# sns.kdeplot(areas)

In [ ]:
# (areas < np.mean(areas) - 2 * np.std(areas)).sum()